
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dudolllik
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: ProjDiary_development

test:
  <<: *default
  database: ProjDiary_test